name: marquina
favicon: null
layout_spectrum: 0.10357719217427075
typography_spectrum: 0.5400467438157648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff5dd'
    - '#020202'
    - '#f7a349'
    - '#c90000'
    - '#70676c'
  brandStrength: 0.9327898323535919
  lightness: 0.2627304312773049
  saturation: 0.203353340504691
  rhythmicContrast: 0.2676640707068145
purpose: []
