name: marquina
favicon: null
layout_spectrum: 0.6298
typography_spectrum: 0.5400467438157648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffae8'
    - '#0b0502'
    - '#636e82'
    - '#880000'
    - '#d69b9f'
  brandStrength: 0.5
  lightness: 0.2627304312773049
  saturation: 0.203353340504691
  rhythmicContrast: 0.2676640707068145
purpose: []
